services:
  web:
    image: registry.diginfra.net/tsd/pyfat-http:latest
    hostname: pyfat-http
    container_name: pyfat-http
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pyfat-http.rule=Host(`pyfat-http.dev.clariah.nl`)"
        - "traefik.http.routers.pyfat-http.entrypoints=http"
        - "traefik.http.services.pyfat-http.loadbalancer.server.port=8000"
    networks:
        - traefik-public

networks:
  traefik-public:
    external: true