services:
  web:
    image: registry.diginfra.net/tsd/pyfat-http:latest
    hostname: pyfat-http
    container_name: pyfat-http
    environment:
      - TTL_PATH=/srv/vlo-data/ttl
      - HTML_PATH=/srv/vlo-data/html
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pyfat-http.rule=Host(`pyfat-http.datasets.dev.clariah.nl`)"
        - "traefik.http.routers.pyfat-http.entrypoints=http"
        - "traefik.http.services.pyfat-http.loadbalancer.server.port=8000"
    volumes:
      - harvest-data-prod:/srv/vlo-data
    networks:
        - traefik-public

volumes:
    harvest-data-prod:
      external: True

networks:
  traefik-public:
    external: true